---
# Inventory for local testing
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      
  children:
    incus_servers:
      hosts:
        localhost:
          incus_remote: local
          incus_project: default
    
    bastion_servers:
      hosts:
        localhost:
          bastion_admin_user: bastion-admin
          bastion_ssh_port: 2222
